// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/Banner.vue')['default']
    HeroSelect: typeof import('./src/components/HeroSelect.vue')['default']
    HeroSkins: typeof import('./src/components/HeroSkins.vue')['default']
    NavBanner: typeof import('./src/components/NavBanner.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('./src/components/Toast/index.vue')['default']
    VideoInfo: typeof import('./src/components/VideoInfo.vue')['default']
  }
}
